2022-02-03 17:07:40,189 INFO    MainThread:2387 [wandb_setup.py:_flush():71] setting env: {}
2022-02-03 17:07:40,190 INFO    MainThread:2387 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-03 17:07:40,190 INFO    MainThread:2387 [wandb_init.py:_log_setup():371] Logging user logs to /Users/liwenyu/Documents/GitHub/RTDM/wandb/run-20220203_170740-3lnsuvqt/logs/debug.log
2022-02-03 17:07:40,190 INFO    MainThread:2387 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/liwenyu/Documents/GitHub/RTDM/wandb/run-20220203_170740-3lnsuvqt/logs/debug-internal.log
2022-02-03 17:07:40,190 INFO    MainThread:2387 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fa0ee85dd90>
2022-02-03 17:07:40,191 INFO    MainThread:2387 [wandb_init.py:init():404] calling init triggers
2022-02-03 17:07:40,191 INFO    MainThread:2387 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-03 17:07:40,191 INFO    MainThread:2387 [wandb_init.py:init():449] starting backend
2022-02-03 17:07:40,191 INFO    MainThread:2387 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-02-03 17:07:40,206 INFO    MainThread:2387 [backend.py:ensure_launched():199] starting backend process...
2022-02-03 17:07:40,213 INFO    MainThread:2387 [backend.py:ensure_launched():204] started backend process with pid: 2394
2022-02-03 17:07:40,215 INFO    MainThread:2387 [wandb_init.py:init():458] backend started and connected
2022-02-03 17:07:40,294 INFO    MainThread:2387 [wandb_run.py:_label_probe_notebook():917] probe notebook
2022-02-03 17:07:40,296 INFO    MainThread:2387 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-03 17:07:40,296 INFO    MainThread:2387 [wandb_init.py:init():519] updated telemetry
2022-02-03 17:07:40,318 INFO    MainThread:2387 [wandb_init.py:init():549] communicating current version
2022-02-03 17:07:41,845 INFO    MainThread:2387 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-03 17:07:41,847 INFO    MainThread:2387 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-02-03 17:07:42,042 INFO    MainThread:2387 [wandb_init.py:init():592] starting run threads in backend
2022-02-03 17:07:46,371 INFO    MainThread:2387 [wandb_run.py:_console_start():1816] atexit reg
2022-02-03 17:07:46,372 INFO    MainThread:2387 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2022-02-03 17:07:46,373 INFO    MainThread:2387 [wandb_run.py:_redirect():1727] Wrapping output streams.
2022-02-03 17:07:46,376 INFO    MainThread:2387 [wandb_run.py:_redirect():1751] Redirects installed.
2022-02-03 17:07:46,376 INFO    MainThread:2387 [wandb_init.py:init():619] run started, returning control to user process
2022-02-03 17:07:46,380 INFO    MainThread:2387 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-03 17:07:46,380 INFO    MainThread:2387 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-03 17:07:46,420 INFO    MainThread:2387 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-03 17:07:47,423 INFO    MainThread:2387 [wandb_config.py:__setitem__():144] config set gamma = 0.99 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa0eff29f70>>
2022-02-03 17:07:47,439 INFO    MainThread:2387 [wandb_run.py:_config_callback():962] config_cb gamma 0.99 None
2022-02-03 17:07:47,441 INFO    MainThread:2387 [wandb_config.py:__setitem__():144] config set nenvs = 8 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa0eff29f70>>
2022-02-03 17:07:47,442 INFO    MainThread:2387 [wandb_run.py:_config_callback():962] config_cb nenvs 8 None
2022-02-03 17:07:47,443 INFO    MainThread:2387 [wandb_config.py:__setitem__():144] config set seed = 1 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa0eff29f70>>
2022-02-03 17:07:47,444 INFO    MainThread:2387 [wandb_run.py:_config_callback():962] config_cb seed 1 None
2022-02-03 17:07:47,445 INFO    MainThread:2387 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-03 17:07:47,445 INFO    MainThread:2387 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-03 17:07:47,486 INFO    MainThread:2387 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-03 17:07:47,490 INFO    MainThread:2387 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-03 17:07:47,490 INFO    MainThread:2387 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-03 17:07:47,521 INFO    MainThread:2387 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-03 17:07:48,271 INFO    MainThread:2387 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-03 17:07:48,272 INFO    MainThread:2387 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-03 17:10:26,469 INFO    MainThread:2387 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-03 17:10:27,018 INFO    MainThread:2387 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-03 17:10:27,019 INFO    MainThread:2387 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-03 17:10:43,499 INFO    MainThread:2387 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-03 17:10:43,513 INFO    MainThread:2387 [wandb_setup.py:_flush():71] setting env: {}
2022-02-03 17:10:43,513 INFO    MainThread:2387 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-03 17:10:43,513 INFO    MainThread:2387 [wandb_init.py:_log_setup():371] Logging user logs to /Users/liwenyu/Documents/GitHub/RTDM/wandb/run-20220203_171043-148v142b/logs/debug.log
2022-02-03 17:10:43,513 INFO    MainThread:2387 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/liwenyu/Documents/GitHub/RTDM/wandb/run-20220203_171043-148v142b/logs/debug-internal.log
2022-02-03 17:10:43,514 INFO    MainThread:2387 [wandb_init.py:init():404] calling init triggers
2022-02-03 17:10:43,514 INFO    MainThread:2387 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-03 17:10:43,514 INFO    MainThread:2387 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 3lnsuvqt
2022-02-03 17:10:43,516 INFO    MainThread:2387 [wandb_run.py:finish():1463] finishing run lwyjo/PPO/3lnsuvqt
2022-02-03 17:10:43,648 INFO    MainThread:2387 [jupyter.py:save_history():429] not saving jupyter history
2022-02-03 17:10:43,648 INFO    MainThread:2387 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-03 17:10:43,649 INFO    MainThread:2387 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-03 17:10:43,649 INFO    MainThread:2387 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2022-02-03 17:10:43,649 INFO    MainThread:2387 [wandb_run.py:_restore():1758] restore
2022-02-03 17:10:44,004 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1065
  total_bytes: 1065
}

2022-02-03 17:10:44,206 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1065
  total_bytes: 1065
}

2022-02-03 17:10:44,792 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 1065
  total_bytes: 12060
}

2022-02-03 17:10:44,904 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1065
  total_bytes: 12496
}

2022-02-03 17:10:45,013 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1065
  total_bytes: 12496
}

2022-02-03 17:10:45,120 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 12496
  total_bytes: 12496
}

2022-02-03 17:10:45,227 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 12496
  total_bytes: 12496
}

2022-02-03 17:10:45,334 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 12496
  total_bytes: 12496
}

2022-02-03 17:10:45,437 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 12496
  total_bytes: 12496
}

2022-02-03 17:10:45,543 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 12496
  total_bytes: 12496
}

2022-02-03 17:10:45,882 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 12496
  total_bytes: 12496
}

2022-02-03 17:10:46,279 INFO    MainThread:2387 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 12496
  total_bytes: 12496
}
local_info {
}

2022-02-03 17:10:47,677 INFO    MainThread:2387 [wandb_run.py:_append_files():2184] logging synced files
